### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by Christian-Meyer** [Energinet-DataHub/geh-metering-point#37]
### Describe the solution you'd like.
- [x] See [this comment ](https://github.com/Energinet-DataHub/geh-metering-point/issues/37#issuecomment-831781583) for updated list of validations
- [x] We must take into consideration what rules apply to what metering point types (according to attached master data reference sheet(https://github.com/Energinet-DataHub/geh-metering-point/issues/37#issuecomment-832475687)) 

### Describe alternatives you've considered.
- [ ] Unit tests for the different validation rules

**Comment by erduna** [comment]
All relevant rules described below. I have removed rules not relevant for DH3(GEH) and adjusted rules which included things not relevant any more (eg. things related to profiled MPs and electrical heating). Rules I am investigating further have been marked and this post will be edited as I know more:


- The identification of a metering point is mandatory
- The identification of a metering point is a valid GSRN/EAN18   code (checksum) that starts with digits '57'
- The identification of a metering point is unique within CCR   (also historically)
- The metering grid area of a metering point is mandatory
- The metering grid area of a metering point must be an existing   metering grid area
- The metering grid area of a metering point must belong to the   correct grid operator
- The occurrence of a metering point is mandatory
- The occurrence of a metering point has format YYYY-MM-DD   HH:MI:SS (UTC+0)
- The energy business process of a metering point is mandatory
- The metering grid area of a metering point consists of exactly 3   digits
- The type of a metering point is mandatory
- The type of a metering point has domain values E17   (Consumption), E18 (Production), E20 (Exchange), D01 (VE production), D04   (Surplus production group 6), D05 (Net production), D06 (Supply to grid), D07   (Consumption from grid), D08 (Wholesale services / information), D09 (Own   production), D10 (Net from grid), D11 (Net to grid), D12 (Total consumption),   D13 (Grid loss correction), D14 (Electrical heating), D15 (Net consumption),   D17 (Other consumption), D18 (Other production), D20 (Exchange - Reactive energy),   D02 (Analysis), D99 (Internal use)
- The physical status of a metering point is mandatory
- The physical status of a metering point has domain values D02   (Closed down), D03 (New), E22 (Connected), E23 (Disconnected)
- The street code of a metering point consists of exactly 4 digits   in the range 0001 to 9999
- The street name of a metering point consists of maximal 40   characters
- If country code is DK then the building number of a metering   point consists of maximal 4 characters (range 1-999, A-Z, Æ, Ø, Å capitals   only and no spaces), otherwise the building number consists of maximal 6   characters.
- The floor identification of a metering point consists of maximal   4 characters
- The room identification of a metering point consists of maximal   4 characters
- The city name of a metering point is mandatory
- The city name of a metering point consists of maximal 25   characters
- The post code of a metering point is mandatory
- If country code is DK then the post code of a metering point   consists of exactly 4 digits in the range 0000 to 9999 otherwise the post   code consists of maximal 10 characters.
- The city sub division name of a metering point consists of   maximal 34 characters
- The municipality code of a metering point consists of exactly 3   digits in the range 100 to 999
- The country name of a metering point has domain values DK   (Denmark)
- The settlement method of a metering point is mandatory
- The settlement method of a metering point has domain values E02 (Non profiled), D01 (Flex)
- The reading characteristics of a metering point is not allowed
- The meter reading occurrence of a metering point is mandatory
- The meter reading occurrence of a metering point has domain   values P1Y (Every year), P1M (Every month), PT1H (Every hour), PT15M (Every 15 minutes)
- The source metering grid area of a metering point is mandatory        - type E20 or      - type D20 and metering point is coupled to a parent or      - not allowed (D20 standalone and other types)
- The source grid area of a metering point must be an existing   metering grid area
- The target metering grid area of a metering point is   mandatory     - type E20 or     - type D20 and metering point is coupled to parent (E20) or     - not allowed (D20 standalone and other types)
- The target grid area of a metering point must be an existing   metering grid area
- The net settlement group of a metering point is mandatory
- The net settlement group of a metering point has domain values   0, 1, 2, 3, 4, 5, 6, 7 and 99
- The power plant of a metering point is mandatory
- The power plant of a metering point is a valid GSRN/EAN18 code   (checksum) that starts with digits ´57´
- The product of a metering point is mandatory
- The product of a metering point has domain values 8716867000030   (Active energy), 8716867000047 (Reactive energy), 8716867000016 (Active   power), 8716867000023 (Reactive power), 5790001330606 (Fuel quantity),   5790001330590 (Tariff)
- The energy time series measure unit of a metering point is   mandatory
- The street name of a metering point is mandatory
_- Only  a non-profiled/flex metering point in net settlement group 6 with physical status other than NEW can have up to 12 scheduled meter reading dates (else not allowed) (Investigating if relevant)_
- The 2nd to 12th scheduled meter reading dates of a metering   point are empty if the first scheduled meter reading date is not available
_- The meter reading occurrence of a flex-settled or non-profiled   settled metering point must be PT1H (Investigating if correct)_
- The product of a newly established metering point has default value 8716867000030 (Active energy) if metering point type not VE Production   (D01), Analysis (D02), Exchange - Reactive energy (D20) or Internal use (D99)
- The energy time series measure unit of a metering point has   domain values K3 (kVArh), KWH (kWh), KWT (kW), MAW (MW), MWH (MWh), TNE   (Tonne), Z03 (MVAr), Z14 (Danish tariff code)
- The occurrence of a metering point has format YYYY-MM-DD   00:00:00 (local time)
_- The sender of a message is mandatory (Handled in api gateway?)_
- The sender of a message must currently be an existing and active   market party (company)
_- The recipient of a message is mandatory (Handled in api gateway?)_
- The recipient of a message must currently be an existing and active market party (company)
- The sender role of a message must be DDM (Grid access provider)
_- The energy business process of a message must be E02 (New metering point) (Handled in API gateway?)_
- The data information must be received within the correct time period
- The identification of a transaction is mandatory
- The identification of a transaction is unique for the sending market player **(Note this confirms message transaction IDs are not globally unique, but unique per market participant)**
- The Metering Point created must become new (connected if metering point type is D04, D14 or D15 when established)
- The meter reading occurrence of a metering point must be PT1H or PT15M
- The meter reading occurrence of a metering point must be P1M, PT1H or PT15M _(Investigating this and rule above, as it is either missing some info or one is redundant)_
- The sub type of a metering point is mandatory
- The document type of a message must be E58 (Request update master data metering point) _(In api gateway?)_
- The hourly time series of a metering point has domain values 1   (Yes), 0 (No) _(Investigating)_
- The counter digits of a metering point's meter consists of maximal 5 characters _(Investigating if meter rules are relevant still)_
- The counter multiply factor of a metering point's meter consists   of maximal 12 digits with format (8.4) _(As above)_
- The counter type of a metering point's meter has domain values   D01 (Accumulated), D02 (Balanced) _(as above)_
- The counter unit of a metering point's meter has domain values   KWH (Kilowatt-hour), MWH (Megawatt-hour) _(as above)_
- The meter number of a metering point consists of maximal 15   characters _(as above)_
- The kilowatt power limit of a metering point consists of maximal   6 digits
- The ampere power limit of a metering point consists of maximal 6   digits
- The first consumer party name of a newly established metering   point has default value '(ukendt)' (=unknown)
- The electrical heating of a newly established metering point has   default value 0 (No)
- The location description of a metering point consists of maximal   60 characters
- The sub type of a metering point has domain values D01   (Physical), D02 (Virtual), D03 (Calculated)
- The Metering Point to which the master data applies must have a   registered meter if subtype equals Physical
- The Metering Point to which the master data applies cannot have   a registered meter if subtype differs from Physical.
- Only a Metering Point in group 1 and 2 can act as a parent (i.e.   have coupled childs).
- Only a Metering Point in group 3 or 4 can act as a child of   group 1 (i.e. have a coupled parent).
- Only a Metering Point in group 5 can act as a child of group 2   (i.e. have a coupled parent).
- The Grid Area of a child Metering Point must be the same as its parent
- The master data attribute is mandatory for the type of metering   point
- The master data attribute is not allowed for the type of   metering point
- The master data attribute is mandatory for the type of metering   point (if profiled MP, else not allowed)
- The master data attribute is mandatory for the type of metering   point (if physical MP, else not allowed) _(Above for rules make no sense, investigating)_
- The address wash instructions a metering point has domain values D01 (Washable),   D02 (Not washable)
- The capacity of a metering point consists of maximal 8 characters. Only digits and an optional decimal point are allowed.
- The connection type of a metering point has domain values D01   (Direct connected), D02 (Installation connected)
- The disconnection type of a metering point has domain values D01   (Remote disconnection), D02 (Manual disconnection)
- The   address wash instructions of a metering point is mandatory
- The capacity of a metering point is mandatory if net settlement   group is not 0, else optional.
- The connection type of a metering point is mandatory if net   settlement group is not 0 (else not allowed)
- The disconnection type of a metering point is mandatory
- The measure unit must be kWh if the master data does not apply   to a metering point of type VE Production (D01), Analysis (D02), Other   consumption (D17), Other production (D18), Exchange - Reactive energy (D20)   or Internal use (D99)
- Only 1   scheduled meter reading date may exist if the master data applies to a   metering point with net settlement    group 6
- Hourly time series can only be true if meter reading occurrence is Hourly (PT1H)
- If a   Consumption metering point (E17) is in net settlement group 1 or 2 then the   settlement method must be either Non-profiled (E02) or Flex settled (D01).
- If a   metering point  is in net settlement   group 4, 5 or 6 then connection type must be Installation connected (D02).
- If a Consumption (E17) or Production (E18) metering point is not   in net settlement group 0 or 99 then sub type must be Virtual (D02) or   Calculated (D03).
- For an Own production (D09) child metering point for which the parent metering point is not in net settlement group 0 or 99 the sub type   must be Virtual (D02) or Calculated (D03).
- If a Consumption metering point (E17) is not in net settlement group  0 or 99 then a power plant is   required.
- Total consumption metering points (D12) must be Virtual (D02) or   Calculated (D03).
- If type of metering point is Net consumption (D15) then meter reading occurrence   must be Hourly (PT1H).
- If type of metering point is Net consumption (D15) then sub type   must be Calculated (D03).
- The AssetType has domain values D01 – D07, D10 - D14, D17, D19,   D20 or D99
- For Production metering point (E18) the AssetType is mandatory.   For a Consumption metering point (E17) in net settlement group not 0 the   AssetType is mandatory, else optional.      For other TypeOfMP not allowed.
- The   format of the DARReference of the metering point should comply with the   generic UUID format
- The product must be Reactive energy (8716867000047) if the   metering point is of type Exchange - Reactive energy (D20)
- The energy time series measure unit must be kWh or MWh if the   master data applies to a metering point of type Other consumption (D17) or   Other production (D18)
- If type of metering point is Other consumption (D17) or Other   production (D18) then sub type must be Physical (D01) or Virtual (D02).
- The meter reading occurrence of a D20 child metering point must   be the same as the E20 parent metering point.
- Subtype of a D20 metering point must be Physical (D01)
- The energy time series measure unit of a D20 metering point must   be K3 (kVArh)
- If a D20 child metering point is coupled to a parent, the parent   (E20) must have subtype Physical (D01)
- It is not allowed to provide the source metering grid area if a   metering point of type is Exchange - Reactive energy (D20).
- It is not allowed to provide the target metering grid area if a   metering point of type is Exchange - Reactive energy (D20).

**Comment by erduna** [comment]
I have updated and uploaded master data reference sheet. It conforms to the latest business process guide updates.

[Stamdata engros opret vers. 3.7.6.xlsx](https://github.com/Energinet-DataHub/geh-metering-point/files/6425543/Stamdata.engros.opret.vers.3.7.6.xlsx)

**Comment by erduna** [comment]
Updated rule list to reflect mandatory/not allowed fields as shown in uploaded reference sheet

**Comment by Christian-Meyer** [comment]
The rules in the comment above have been moved into  #71.
This story is the refactor to fluent validation.

**Comment by erduna** [comment]
Being implemented by #71
